language: python
cache: pip
dist: bionic
python:
  - "2.7"
  - "3.7"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - tor
      - xvfb
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python checkdeps.py
  - xvfb-run src/bitmessagemain.py -t
  - python setup.py test
