language: python
dist: bionic
cache: pip
python:
  - "2.7"
  - "2.7_with_system_site_packages"
services:
  - docker
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - xvfb
jobs:
  allow_failures:
    - os: windows
  include:
    - dist: xenial
    - dist: bionic
      if: type = pull_request
      language: generic
      install:
        - docker build -t bm_fedora -f packages/Dockerfile.fedora .
      script:
        - docker run bm_fedora
    - os: osx
      language: generic
    - os: windows
      language: shell
      before_install:
        - choco install python2 tor
        - choco install --ignore-dependencies vcpython27
        - python -m pip install --upgrade pip
        - wget -c -nc -nv --content-disposition https://github.com/Bitmessage/ThirdPartyLibraries/blob/master/Win64OpenSSL-1_0_2t.exe?raw=true
        - powershell -Command "Start-Process -FilePath Win64OpenSSL-1_0_2t.exe -ArgumentList '/q /norestart /silent /verysilent /sp- /suppressmsgboxes /dir=C:\OpenSSL-Win64' -Wait"
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
        - OPENSSL_DIR="c:\\OpenSSL-Win64"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python checkdeps.py
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    xvfb-run src/bitmessagemain.py -t;
    else
    python src/bitmessagemain.py -t;
    fi
  - python setup.py test
