language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - tor
      - xvfb
jobs:
  allow_failures:
    - os: windows
  include:
    - dist: xenial
    - os: windows
      # if: type = pull_request
      language: shell
      before_install:
        - choco install python2
        - choco install --ignore-dependencies vcpython27
        - python -m pip install --upgrade pip
        - python -m pip install psutil pycrypto
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
install:
  - pip install -r requirements.txt
  - ln -s src pybitmessage  # tests environment
  - python setup.py install
script:
  - python checkdeps.py
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    xvfb-run src/bitmessagemain.py -t;
    else
    export BITMESSAGE_HOME=$(pwd)/$(echo -e "Pou\u017e\u00edvatel");
    mkdir ${BITMESSAGE_HOME};
    python src/bitmessagemain.py -t;
    fi
  - python setup.py test
