language: python
cache: pip
dist: bionic
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - tor
      - xvfb
jobs:
  allow_failures:
    - python: "3.6"
  include:
    - dist: xenial
    - os: osx
      if: tag IS present
      language: generic
    - stage: deploy
      python: 2.7_with_system_site_packages
      script: skip
      deploy:
        provider: releases
        token:
          secure: YOUR_API_KEY_ENCRYPTED
        file:
          - dist/pybitmessage-${VERSION}.tar.gz
          - dist/pybitmessage_${VERSION}-1_amd64.deb
        cleanup: false
        draft: true
        on:
          tags: true
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python checkdeps.py
  - xvfb-run src/bitmessagemain.py -t
  - python setup.py test
before_deploy:
  - sudo apt-get install -yq python-stdeb fakeroot python-all-dev dh-python debhelper libssl-dev
  - python setup.py sdist
  - export VERSION=$(python setup.py --version)
  - python setup.py --command-packages=stdeb.command bdist_deb
  - mv deb_dist/pybitmessage_${VERSION}-1_amd64.deb dist/
