language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - tor
      - xvfb
jobs:
  allow_failures:
    - python: "3.6"
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      language: generic
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pip install -r requirements.txt;
    else
    pip install psutil pycrypto;
    fi
  - python setup.py install
script:
  - python checkdeps.py
  - xvfb-run src/bitmessagemain.py -t
  - python setup.py test
